packages:
  - "docs"
  - "admin"
  - "apps/*"
  - "packages/*"
  - "scripts/*"
catalog:
  "@tsconfig/node22": "^22.0.0"
  "@types/jsdom": "^21.1.7"
  "@types/node": "^22.9.0"
  "@vitejs/plugin-vue": "^5.1.4"
  "@vitejs/plugin-vue-jsx": "^4.0.1"
  "@vitest/eslint-plugin": "1.1.7"
  "@vue/eslint-config-prettier": "^10.1.0"
  "@vue/eslint-config-typescript": "^14.1.3"
  "@vue/test-utils": "^2.4.6"
  "@vue/tsconfig": "^0.5.1"
  "@clack/prompts": "^0.8.1"
  "@manypkg/get-packages": "^2.2.2"
  "@changesets/cli": "^2.27.9"
  "@vite-pwa/vitepress": "^0.5.3"
  "markdown-it-custom-attrs": "^1.0.2"
  "vitepress": "^1.5.0"
  "turbo": "^2.3.0"
  "unbuild": "^2.0.0"
  "chalk": "^5.3.0"
  "consola": "^3.2.3"
  "execa": "^9.5.1"
  "find-up": "^7.0.0"
  "cac": "^6.7.14"
  "pinia": "^2.2.6"
  "vue": "^3.5.12"
  "vue-router": "^4.4.5"
  "eslint": "^9.14.0"
  "eslint-plugin-vue": "^9.30.0"
  "jsdom": "^25.0.1"
  "npm-run-all2": "^7.0.1"
  "prettier": "^3.3.3"
  "typescript": "~5.6.3"
  "vite": "^5.4.10"
  "vite-plugin-vue-devtools": "^7.5.4"
  "vitest": "^2.1.4"
  "vue-tsc": "^2.1.10"
