packages:
  - docs
  - admin
  - apps/*
  - packages/*
  - scripts/*
catalog:
  '@changesets/cli': ^2.27.9
  '@clack/prompts': ^0.8.1
  '@iconify/tailwind': ^1.1.3
  '@manypkg/get-packages': ^2.2.2
  '@tailwindcss/nesting': 0.0.0-insiders.565cd3e
  '@tailwindcss/typography': ^0.5.15
  '@tsconfig/node22': ^22.0.0
  '@types/lodash.clonedeep': ^4.5.9
  '@types/node': ^22.9.1
  '@vite-pwa/vitepress': ^0.5.3
  '@vitejs/plugin-vue': ^5.2.0
  '@vitejs/plugin-vue-jsx': ^4.1.0
  '@vitest/eslint-plugin': 1.1.7
  '@vue/eslint-config-prettier': ^10.1.0
  '@vue/eslint-config-typescript': ^14.1.3
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.5.1
  '@radix-icons/vue': ^1.0.0
  autoprefixer: ^10.4.20
  cac: ^6.7.14
  chalk: ^5.3.0
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  consola: ^3.2.3
  dotenv: ^16.4.5
  eslint: ^9.15.0
  eslint-plugin-vue: ^9.31.0
  execa: ^9.5.1
  find-up: ^7.0.0
  happy-dom: ^15.11.6
  lodash.clonedeep: ^4.5.0
  lucide-vue-next: ^0.460.0
  minimatch: ^10.0.1
  markdown-it-custom-attrs: ^1.0.2
  npm-run-all2: ^7.0.1
  pinia: ^2.2.6
  postcss: ^8.4.49
  prettier: ^3.3.3
  radix-vue: ^1.9.10
  tailwind-merge: ^2.5.4
  tailwindcss: ^3.4.15
  tailwindcss-animate: ^1.0.7
  turbo: ^2.3.0
  typescript: ~5.6.3
  unbuild: ^2.0.0
  vite: ^5.4.11
  vite-plugin-pwa: ^0.21.0
  vite-plugin-vue-devtools: ^7.6.4
  vite-plugin-lazy-import: ^1.0.7
  vitepress: ^1.5.0
  vitest: ^2.1.5
  vue: ^3.5.13
  vue-router: ^4.4.5
  vue-tsc: ^2.1.10
